jwt:
  secret: '[a-zA-Z0-9._]^+$eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9TJVA95OrM7E2cBab30RMHrHDcEfxjoYZgeFONFh7HgQ$'
spring:
  datasource:
    password: ''
    url: jdbc:mysql://localhost:3306/processus_de_positionnement
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    generate-ddl : true
    